# Generated by Django 6.0.3 on 2026-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_dropoff_lat_ride_dropoff_lng_ride_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
