# Generated by Django 6.0.3 on 2026-04-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
